export const districts = {
    "Dhaka": [
        "Dhamrai",
        "Dohar",
        "Keraniganj",
        "Nawabganj",
        "Savar",
        "ধামরাই",
        "দোহার",
        "কেরানীগঞ্জ",
        "নবাবগঞ্জ",
        "সাভার"
    ],
    "Faridpur": [
        "Alfadanga",
        "Bhanga",
        "Boalmari",
        "Char Bhadrasan",
        "Faridpur Sadar",
        "Madhukhali",
        "Nagarkanda",
        "Sadarpur",
        "Saltha",
        "আলফাডাঙ্গা",
        "ভাঙ্গা",
        "বোয়ালমারী",
        "চরভদ্রাসন",
        "ফরিদপুর সদর",
        "মধুখালী",
        "নগরকান্দা",
        "সদরপুর",
        "সালথা"
    ],
    "Gazipur": [
        "Gazipur Sadar",
        "Kaliakair",
        "Kaliganj",
        "Kapasia",
        "Sreepur",
        "গাজীপুর সদর",
        "কালিয়াকৈর",
        "কালিগঞ্জ",
        "কাপাসিয়া",
        "শ্রীপুর"
    ],
    "Gopalganj": [
        "Gopalganj Sadar",
        "Kashiani",
        "Kotalipara",
        "Muksudpur",
        "Tungipara",
        "গোপালগঞ্জ সদর",
        "কাশিয়ানী",
        "কোটালিপাড়া",
        "মুকসুদপুর",
        "টুঙ্গিপাড়া"
    ],
    "Kishoreganj": [
        "Austagram",
        "Bajitpur",
        "Bhairab",
        "Hossainpur",
        "Itna",
        "Karimganj",
        "Katiadi",
        "Kishoreganj Sadar",
        "Kuliarchar",
        "Mithamain",
        "Nikli",
        "Pakundia",
        "Tarail",
        "অষ্টগ্রাম",
        "বাজিতপুর",
        "ভৈরব",
        "হোসেনপুর",
        "ইটনা",
        "করিমগঞ্জ",
        "কটিয়াদি",
        "কিশোরগঞ্জ সদর",
        "কুলিয়ারচর",
        "মিঠামইন",
        "নিকলী",
        "পাকুন্দিয়া",
        "তাড়াইল"
    ],
    "Madaripur": [
        "Kalkini",
        "Madaripur Sadar",
        "Rajoir",
        "Shibchar",
        "কালকিনি",
        "মাদারীপুর সদর",
        "রাজৈর",
        "শিবচর"
    ],
    "Manikganj": [
        "Daulatpur",
        "Ghior",
        "Harirampur",
        "Manikganj Sadar",
        "Saturia",
        "Shibalaya",
        "Singair",
        "দৌলতপুর",
        "ঘিওর",
        "হরিরামপুর",
        "মানিকগঞ্জ সদর",
        "সাটুরিয়া",
        "শিবালয়",
        "সিংগাইর"
    ],
    "Munshiganj": [
        "Gazaria",
        "Lohajang",
        "Munshiganj Sadar",
        "Sirajdikhan",
        "Sreenagar",
        "Tongibari",
        "গজারিয়া",
        "লৌহজং",
        "মুন্সিগঞ্জ সদর",
        "সিরাজদিখান",
        "শ্রীনগর",
        "টংগিবাড়ি"
    ],
    "Narayanganj": [
        "Araihazar",
        "Bandar",
        "Narayanganj Sadar",
        "Rupganj",
        "Sonargaon",
        "আড়াইহাজার",
        "বন্দর",
        "নারায়ণগঞ্জ সদর",
        "রূপগঞ্জ",
        "সোনারগাঁ"
    ],
    "Narsingdi": [
        "Belabo",
        "Monohardi",
        "Narsingdi Sadar",
        "Palash",
        "Raipura",
        "Shibpur",
        "বেলাবো",
        "মনোহরদী",
        "নরসিংদী সদর",
        "পলাশ",
        "রায়পুরা",
        "শিবপুর"
    ],
    "Rajbari": [
        "Baliakandi",
        "Goalanda",
        "Kalukhali",
        "Pangsha",
        "Rajbari Sadar",
        "বালিয়াকান্দি",
        "গোয়ালন্দ",
        "কালুখালী",
        "পাংশা",
        "রাজবাড়ী সদর"
    ],
    "Shariatpur": [
        "Bhedarganj",
        "Damudya",
        "Gosairhat",
        "Naria",
        "Shariatpur Sadar",
        "Zajira",
        "ভেদরগঞ্জ",
        "ডামুড্যা",
        "গোসাইরহাট",
        "নড়িয়া",
        "শরীয়তপুর সদর",
        "জাজিরা"
    ],
    "Tangail": [
        "Basail",
        "Bhuapur",
        "Delduar",
        "Dhanbari",
        "Ghatail",
        "Gopalpur",
        "Kalihati",
        "Madhupur",
        "Mirzapur",
        "Nagarpur",
        "Sakhipur",
        "Tangail Sadar",
        "বাসাইল",
        "ভূঞাপুর",
        "দেলদুয়ার",
        "ধনবাড়ী",
        "ঘাটাইল",
        "গোপালপুর",
        "কালিহাতী",
        "মধুপুর",
        "মির্জাপুর",
        "নাগরপুর",
        "সখিপুর",
        "টাঙ্গাইল সদর"
    ],
    "Mymensingh": [
        "Bhaluka",
        "Dhobaura",
        "Fulbaria",
        "Gaffargaon",
        "Gauripur",
        "Haluaghat",
        "Ishwarganj",
        "Mymensingh Sadar",
        "Muktagachha",
        "Nandail",
        "Phulpur",
        "Trishal",
        "ভালুকা",
        "ধোবাউড়া",
        "ফুলবাড়িয়া",
        "গফরগাঁও",
        "গৌরীপুর",
        "হালুয়াঘাট",
        "ঈশ্বরগঞ্জ",
        "ময়মনসিংহ সদর",
        "মুক্তাগাছা",
        "নান্দাইল",
        "ফুলপুর",
        "ত্রিশাল"
    ],
    "Netrokona": [
        "Atpara",
        "Barhatta",
        "Durgapur",
        "Kalmakanda",
        "Kendua",
        "Khaliajuri",
        "Madan",
        "Mohanganj",
        "Netrokona Sadar",
        "Purbadhala",
        "আটপাড়া",
        "বারহাট্টা",
        "দুর্গাপুর",
        "কলমাকান্দা",
        "কেন্দুয়া",
        "খালিয়াজুরি",
        "মদন",
        "মোহনগঞ্জ",
        "নেত্রকোনা সদর",
        "পূর্বধলা"
    ],
    "Jamalpur": [
        "Bakshiganj",
        "Dewanganj",
        "Islampur",
        "Jamalpur Sadar",
        "Madarganj",
        "Melandaha",
        "Sarishabari",
        "বকশীগঞ্জ",
        "দেওয়ানগঞ্জ",
        "ইসলামপুর",
        "জামালপুর সদর",
        "মাদারগঞ্জ",
        "মেলান্দহ",
        "সরিষাবাড়ী"
    ],
    "Sherpur": [
        "Jhenaigati",
        "Nakla",
        "Nalitabari",
        "Sherpur Sadar",
        "Sreebardi",
        "ঝিনাইগাতী",
        "নকলা",
        "নালিতাবাড়ী",
        "শেরপুর সদর",
        "শ্রীবরদী"
    ],
    "Chattogram": [
        "Anwara",
        "Banshkhali",
        "Boalkhali",
        "Chandanaish",
        "Fatikchhari",
        "Hathazari",
        "Lohagara",
        "Mirsharai",
        "Patiya",
        "Rangunia",
        "Raozan",
        "Sandwip",
        "Satkania",
        "Sitakunda",
        "আনোয়ার",
        "বাঁশখালী",
        "বোয়ালখালী",
        "চন্দনাইশ",
        "ফটিকছড়ি",
        "হাটহাজারী",
        "লোহাগাড়া",
        "মীরসরাই",
        "পটিয়া",
        "রাঙ্গুনিয়া",
        "রাউজান",
        "সন্দ্বীপ",
        "সাতকানিয়া",
        "সীতাকুণ্ড"
    ],
    "Cox's Bazar": [
        "Chakaria",
        "Cox's Bazar Sadar",
        "Kutubdia",
        "Maheshkhali",
        "Pekua",
        "Ramu",
        "Teknaf",
        "Ukhiya",
        "চকরিয়া",
        "কক্সবাজার সদর",
        "কুতুবদিয়া",
        "মহেশখালী",
        "পেকুয়া",
        "রামু",
        "টেকনাফ",
        "উখিয়া"
    ],
    "Cumilla": [
        "Barura",
        "Brahmanpara",
        "Burichang",
        "Chandina",
        "Chauddagram",
        "Cumilla Adarsha Sadar",
        "Cumilla Sadar Dakshin",
        "Daudkandi",
        "Debidwar",
        "Homna",
        "Laksham",
        "Lalmai",
        "Meghna",
        "Monohorgonj",
        "Muradnagar",
        "Nangalkot",
        "Titas",
        "বরুড়া",
        "ব্রাহ্মণপাড়া",
        "বুড়িচং",
        "চান্দিনা",
        "চৌদ্দগ্রাম",
        "কুমিল্লা আদর্শ সদর",
        "কুমিল্লা সদর দক্ষিণ",
        "দাউদকান্দি",
        "দেবিদ্বার",
        "হোমনা",
        "লাকসাম",
        "লালমাই",
        "মেঘনা",
        "মনোহরগঞ্জ",
        "মুরাদনগর",
        "নাঙ্গলকোট",
        "তিতাস"
    ],
    "Brahmanbaria": [
        "Ashuganj",
        "Bancharampur",
        "Bijoynagar",
        "Brahmanbaria Sadar",
        "Kasba",
        "Nabinagar",
        "Nasirnagar",
        "Sarail",
        "আশুগঞ্জ",
        "বাঞ্ছারামপুর",
        "বিজয়নগর",
        "ব্রাহ্মণবাড়িয়া সদর",
        "কসবা",
        "নবীনগর",
        "নাসিরনগর",
        "সরাইল"
    ],
    "Chandpur": [
        "Chandpur Sadar",
        "Faridganj",
        "Haimchar",
        "Hajiganj",
        "Kachua",
        "Matlab Dakshin",
        "Matlab Uttar",
        "Shahrasti",
        "চাঁদপুর সদর",
        "ফরিদগঞ্জ",
        "হাইমচর",
        "হাজীগঞ্জ",
        "কচুয়া",
        "মতলব দক্ষিণ",
        "মতলব উত্তর",
        "শাহরাস্তি"
    ],
    "Feni": [
        "Chhagalnaiya",
        "Daganbhuiyan",
        "Feni Sadar",
        "Parshuram",
        "Sonagazi",
        "ছাগলনাইয়া",
        "দাগনভূইয়া",
        "ফেনী সদর",
        "পরশুরাম",
        "সোনাগাজী"
    ],
    "Lakshmipur": [
        "Kamalnagar",
        "Lakshmipur Sadar",
        "Ramganj",
        "Ramgati",
        "Raipur",
        "কমলনগর",
        "লক্ষ্মীপুর সদর",
        "রামগঞ্জ",
        "রামগতি",
        "রায়পুর"
    ],
    "Noakhali": [
        "Begumganj",
        "Chatkhil",
        "Companiganj",
        "Hatiya",
        "Kabirhat",
        "Noakhali Sadar",
        "Senbagh",
        "Subarnachar",
        "Sonaimuri",
        "বেগমগঞ্জ",
        "চাটখিল",
        "কোম্পানীগঞ্জ",
        "হাতিয়া",
        "কবিরহাট",
        "নোয়াখালী সদর",
        "সেনবাগ",
        "সুবর্ণচর",
        "সোনাইমুড়ী"
    ]
}